[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "playground"
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "56.2.0" }
parquet = { version = "56.2.0", features = ["arrow", "encryption"] }
parquet-key-management = { version = "0.4.0" }
pyo3 = "0.26.0"
pyo3-arrow = "0.12.0"
