name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  schedule:
    - cron: "43 3 * * *"

permissions:
  contents: read

jobs:
  lint-rust:
    name: Lint Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: cargo-cache-lint-rust-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-lint-rust-
      - name: Format check
        run: cargo fmt --verbose --check
      - name: Clippy
        run: cargo clippy --all-features --verbose -- --deny warnings

  lint-toml:
    name: Lint TOML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install taplo
        run: curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-x86_64.gz | gzip -d - | sudo install -m 755 /dev/stdin /usr/local/bin/taplo
      - name: Format check
        run: taplo format --check
      - name: Lint
        run: taplo lint

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: cargo-cache-docs-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-docs-
      - name: Build docs
        run: cargo doc --all-features --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: "-Dwarnings"

  test:
    name: Build and Test
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: cargo-cache-test-${{ matrix.runner }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-test-${{ matrix.runner }}-
      - name: Build
        run: cargo build --all-features --verbose
      - name: Test
        run: cargo test --all-features --verbose
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Integration Test
        run: ./ci/run_integration_tests.sh

  msrv:
    name: Verify minimum supported Rust version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: cargo-cache-msrv-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-msrv-
      - name: Write Cargo.lock
        run: cp Cargo.lock.msrv Cargo.lock
      - name: Install cargo-msrv
        run: cargo install --locked cargo-msrv
      - name: Verify MSRV
        run: cargo msrv verify --all-features --manifest-path parquet-key-management/Cargo.toml

  # A single job that succeeds if all jobs listed under 'needs' succeed.
  # This allows to configure a single job as a required check.
  # The 'needed' jobs then can be changed through pull-requests.
  all-jobs-succeeded:
    name: All jobs succeeded
    if: always()
    # the if clauses below have to reflect the number of jobs listed here
    needs:
      - lint-rust
      - lint-toml
      - docs
      - test
      - msrv
    env:
      RESULTS: ${{ join(needs.*.result, ',') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Success"
        # we expect all required jobs to have success result
        if: env.RESULTS == 'success,success,success,success,success'
        run: true
        shell: bash
      - name: "Failure"
        # we expect all required jobs to have success result, fail otherwise
        if: env.RESULTS != 'success,success,success,success,success'
        run: false
        shell: bash

  publish:
    name: Publish release
    if: ${{ !github.event.repository.fork && startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - all-jobs-succeeded
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Validate version
        run: |
          TAG_VERSION="${{ github.ref_name }}"
          CARGO_VERSION="v$(grep '^version = ' Cargo.toml | cut -d '"' -f 2)"
          if [ "${TAG_VERSION}" != "${CARGO_VERSION}" ]; then
            echo "Tag version (${TAG_VERSION}) does not match version from Cargo (${CARGO_VERSION})"
            exit 1
          fi
      - name: Cargo publish
        run: cargo publish --verbose
        working-directory: ./parquet-key-management
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
